# Generated by Django 6.0.2 on 2026-03-02 02:02

import django.db.models.deletion
import django.db.models.manager
import recurrence.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0004_alter_invitation_role_alter_membership_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('location', models.CharField(blank=True, max_length=300, verbose_name='location')),
                ('start_datetime', models.DateTimeField(verbose_name='start date/time')),
                ('end_datetime', models.DateTimeField(verbose_name='end date/time')),
                ('is_all_day', models.BooleanField(default=False, verbose_name='all day')),
                ('recurrence', recurrence.fields.RecurrenceField(blank=True, null=True)),
                ('category', models.CharField(choices=[('worship', 'Worship'), ('fellowship', 'Fellowship'), ('outreach', 'Outreach'), ('youth', 'Youth'), ('other', 'Other')], default='other', max_length=20, verbose_name='category')),
                ('is_published', models.BooleanField(default=True, verbose_name='published')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
                'ordering': ['start_datetime'],
            },
            managers=[
                ('event_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role_name', models.CharField(max_length=100, verbose_name='role name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('slots_needed', models.PositiveIntegerField(default=1, verbose_name='slots needed')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_slots', to='events.event', verbose_name='event')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'volunteer slot',
                'verbose_name_plural': 'volunteer slots',
                'ordering': ['role_name'],
            },
        ),
        migrations.CreateModel(
            name='VolunteerSignup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('tentative', 'Tentative'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20, verbose_name='status')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_signups', to=settings.AUTH_USER_MODEL, verbose_name='volunteer')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signups', to='events.volunteerslot', verbose_name='slot')),
            ],
            options={
                'verbose_name': 'volunteer signup',
                'verbose_name_plural': 'volunteer signups',
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['team', 'start_datetime'], name='event_team_start'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['team', 'is_published', 'start_datetime'], name='event_team_pub_start'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['category'], name='event_category'),
        ),
        migrations.AlterUniqueTogether(
            name='volunteersignup',
            unique_together={('slot', 'volunteer')},
        ),
    ]
