# Generated by Django 6.0.2 on 2026-03-02 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('teams', '0004_alter_invitation_role_alter_membership_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RotationSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('slot_role_name', models.CharField(max_length=100, verbose_name='slot role name')),
                ('rotation_strategy', models.CharField(choices=[('round_robin', 'Round Robin'), ('weighted', 'Weighted'), ('manual', 'Manual')], default='round_robin', max_length=20, verbose_name='rotation strategy')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotation_schedules', to='events.event', verbose_name='event')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'rotation schedule',
                'verbose_name_plural': 'rotation schedules',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RotationMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('weight', models.PositiveIntegerField(default=1, verbose_name='weight')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='volunteers.rotationschedule', verbose_name='schedule')),
            ],
            options={
                'verbose_name': 'rotation membership',
                'verbose_name_plural': 'rotation memberships',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='VolunteerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skills', models.JSONField(blank=True, default=list, verbose_name='skills')),
                ('max_services_per_month', models.PositiveIntegerField(default=4, verbose_name='max services per month')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_profiles', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'volunteer profile',
                'verbose_name_plural': 'volunteer profiles',
            },
        ),
        migrations.CreateModel(
            name='ScheduledShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(verbose_name='date')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('declined', 'Declined'), ('swapped', 'Swapped')], default='scheduled', max_length=20, verbose_name='status')),
                ('reminder_sent', models.BooleanField(default=False, verbose_name='reminder sent')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_shifts', to='events.event', verbose_name='event')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='volunteers.rotationschedule', verbose_name='schedule')),
                ('slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_shifts', to='events.volunteerslot', verbose_name='slot')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_shifts', to='volunteers.volunteerprofile', verbose_name='volunteer')),
            ],
            options={
                'verbose_name': 'scheduled shift',
                'verbose_name_plural': 'scheduled shifts',
                'ordering': ['date'],
            },
        ),
        migrations.AddField(
            model_name='rotationschedule',
            name='volunteers',
            field=models.ManyToManyField(related_name='rotation_schedules', through='volunteers.RotationMembership', to='volunteers.volunteerprofile', verbose_name='volunteers'),
        ),
        migrations.AddField(
            model_name='rotationmembership',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotation_memberships', to='volunteers.volunteerprofile', verbose_name='volunteer'),
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(verbose_name='date')),
                ('is_available', models.BooleanField(default=False, verbose_name='available')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='note')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='volunteers.volunteerprofile', verbose_name='volunteer')),
            ],
            options={
                'verbose_name': 'availability',
                'verbose_name_plural': 'availabilities',
                'ordering': ['date'],
            },
        ),
        migrations.AddIndex(
            model_name='volunteerprofile',
            index=models.Index(fields=['team', 'is_active'], name='volprofile_team_active'),
        ),
        migrations.AlterUniqueTogether(
            name='volunteerprofile',
            unique_together={('team', 'user')},
        ),
        migrations.AddIndex(
            model_name='scheduledshift',
            index=models.Index(fields=['volunteer', 'date'], name='shift_volunteer_date'),
        ),
        migrations.AddIndex(
            model_name='scheduledshift',
            index=models.Index(fields=['date', 'status'], name='shift_date_status'),
        ),
        migrations.AddIndex(
            model_name='scheduledshift',
            index=models.Index(fields=['date', 'reminder_sent'], name='shift_date_reminder'),
        ),
        migrations.AlterUniqueTogether(
            name='scheduledshift',
            unique_together={('schedule', 'volunteer', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='rotationmembership',
            unique_together={('schedule', 'volunteer')},
        ),
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together={('volunteer', 'date')},
        ),
    ]
