# Generated by Django 6.0.2 on 2026-03-02 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_alter_membership_unique_together_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('coordinator', 'Coordinator'), ('member', 'Member')], default='member', max_length=100),
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('coordinator', 'Coordinator'), ('member', 'Member')], max_length=100),
        ),
    ]
