# Generated by Django 6.0.2 on 2026-03-02 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0004_alter_invitation_role_alter_membership_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageBlast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='subject')),
                ('body', models.TextField(verbose_name='body')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], default='email', max_length=10, verbose_name='channel')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], default='draft', max_length=20, verbose_name='status')),
                ('send_at', models.DateTimeField(blank=True, null=True, verbose_name='scheduled send time')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='actual send time')),
                ('recipient_filter', models.JSONField(default=dict, verbose_name='recipient filter')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_blasts', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'message blast',
                'verbose_name_plural': 'message blasts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageRecipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=10, verbose_name='channel')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('bounced', 'Bounced')], default='pending', max_length=20, verbose_name='status')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='sent at')),
                ('external_id', models.CharField(blank=True, max_length=200, verbose_name='external ID')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('blast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='notifications.messageblast', verbose_name='blast')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_blasts', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'message recipient',
                'verbose_name_plural': 'message recipients',
            },
        ),
        migrations.CreateModel(
            name='ContactPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='phone number')),
                ('receive_email', models.BooleanField(default=True, verbose_name='receive email')),
                ('receive_sms', models.BooleanField(default=False, verbose_name='receive SMS')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_preferences', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'contact preference',
                'verbose_name_plural': 'contact preferences',
                'unique_together': {('team', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='messageblast',
            index=models.Index(fields=['team', 'status'], name='blast_team_status'),
        ),
        migrations.AddIndex(
            model_name='messageblast',
            index=models.Index(fields=['team', '-created_at'], name='blast_team_created'),
        ),
        migrations.AddIndex(
            model_name='messageblast',
            index=models.Index(fields=['status', 'send_at'], name='blast_status_send_at'),
        ),
        migrations.AddIndex(
            model_name='messagerecipient',
            index=models.Index(fields=['blast', 'status'], name='recipient_blast_status'),
        ),
        migrations.AlterUniqueTogether(
            name='messagerecipient',
            unique_together={('blast', 'user', 'channel')},
        ),
    ]
